"""Built-in API interface catalog used by admin interface management."""

COMMON_ERROR_EXAMPLE = {
    "success": False,
    "detail": "请求参数错误或业务校验失败",
}

AUTH_HEADER = [
    {
        "name": "Authorization",
        "type": "string",
        "required": True,
        "description": "Bearer Token，登录成功后返回",
    }
]

SDK_SECURITY_PARAMS = [
    {"name": "app_id", "type": "string", "required": True, "description": "应用 App ID"},
    {"name": "payload", "type": "string", "required": True, "description": "RSA/AES 加密后的业务数据"},
    {"name": "signature", "type": "string", "required": True, "description": "请求签名"},
    {"name": "timestamp", "type": "integer", "required": True, "description": "Unix 时间戳"},
    {"name": "nonce", "type": "string", "required": True, "description": "随机串，防重放"},
]

BUILTIN_API_INTERFACES = [
    {
        "name": "用户注册",
        "interface_key": "user.register",
        "method": "POST",
        "path": "/api/v1/user/register",
        "category": "user",
        "description": "业务侧普通用户注册接口，用于创建可充值和消费积分的用户。",
        "auth_mode": "none",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": [
            {"name": "username", "type": "string", "required": True, "description": "用户名"},
            {"name": "password", "type": "string", "required": True, "description": "登录密码"},
            {"name": "app_id", "type": "string", "required": False, "description": "归属应用 App ID"},
            {"name": "email", "type": "string", "required": False, "description": "邮箱"},
            {"name": "phone", "type": "string", "required": False, "description": "手机号"},
        ],
        "response_params": [
            {"name": "success", "type": "boolean", "required": True, "description": "是否成功"},
            {"name": "data.user_id", "type": "integer", "required": True, "description": "用户 ID"},
            {"name": "data.username", "type": "string", "required": True, "description": "用户名"},
        ],
        "success_example": {"success": True, "message": "账号注册成功", "data": {"user_id": 1, "username": "demo"}},
        "error_example": {"success": False, "detail": "用户名已存在"},
        "remark": "普通用户不提供前台页面，可由业务系统直接调用。",
        "doc_markdown": "用户注册后可使用卡密兑换积分，再通过积分消费接口扣减积分。",
        "sort_order": 10,
    },
    {
        "name": "用户登录",
        "interface_key": "user.login",
        "method": "POST",
        "path": "/api/v1/user/login",
        "category": "user",
        "description": "普通用户登录接口，返回后续积分接口使用的访问令牌。",
        "auth_mode": "none",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": [
            {"name": "username", "type": "string", "required": True, "description": "用户名"},
            {"name": "password", "type": "string", "required": True, "description": "登录密码"},
        ],
        "response_params": [
            {"name": "access_token", "type": "string", "required": True, "description": "访问令牌"},
            {"name": "token_type", "type": "string", "required": True, "description": "令牌类型"},
        ],
        "success_example": {"success": True, "message": "登录成功", "data": {"access_token": "eyJ...", "token_type": "bearer"}},
        "error_example": {"success": False, "detail": "用户名或密码错误"},
        "remark": "登录成功后调用积分接口需携带 Authorization 请求头。",
        "doc_markdown": "业务系统保存 token 后，可查询余额、兑换卡密、消费积分和查询流水。",
        "sort_order": 20,
    },
    {
        "name": "当前用户信息",
        "interface_key": "user.me",
        "method": "GET",
        "path": "/api/v1/user/me",
        "category": "user",
        "description": "获取当前登录普通用户资料。",
        "auth_mode": "bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [],
        "response_params": [
            {"name": "id", "type": "integer", "required": True, "description": "用户 ID"},
            {"name": "username", "type": "string", "required": True, "description": "用户名"},
            {"name": "app_id", "type": "string", "required": False, "description": "归属应用"},
        ],
        "success_example": {"success": True, "message": "获取用户信息成功", "data": {"id": 1, "username": "demo", "app_id": "app_core"}},
        "error_example": {"success": False, "detail": "未登录或登录已过期"},
        "remark": "用于业务侧确认 token 对应用户。",
        "doc_markdown": "该接口不改变积分或卡密状态。",
        "sort_order": 30,
    },
    {
        "name": "查询积分余额",
        "interface_key": "points.balance",
        "method": "GET",
        "path": "/api/v1/user/points/balance",
        "category": "points",
        "description": "查询当前登录用户积分账户余额和累计充值/消费。",
        "auth_mode": "bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [],
        "response_params": [
            {"name": "balance", "type": "integer", "required": True, "description": "当前可用余额"},
            {"name": "total_recharged", "type": "integer", "required": True, "description": "累计充值积分"},
            {"name": "total_consumed", "type": "integer", "required": True, "description": "累计消费积分"},
        ],
        "success_example": {"success": True, "message": "积分余额查询成功", "data": {"balance": 100, "total_recharged": 150, "total_consumed": 50}},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "积分系统闭环中的余额查询接口。",
        "doc_markdown": "适用于业务系统展示用户当前积分余额。",
        "sort_order": 40,
    },
    {
        "name": "卡密兑换积分",
        "interface_key": "points.redeem",
        "method": "POST",
        "path": "/api/v1/user/points/redeem",
        "category": "points",
        "description": "用户使用积分卡密充值，系统生成充值流水并增加积分余额。",
        "auth_mode": "bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "kami_code", "type": "string", "required": True, "description": "积分卡密"},
        ],
        "response_params": [
            {"name": "transaction_id", "type": "string", "required": True, "description": "充值流水号"},
            {"name": "amount", "type": "integer", "required": True, "description": "充值积分"},
            {"name": "balance_after", "type": "integer", "required": True, "description": "充值后余额"},
        ],
        "success_example": {"success": True, "message": "积分充值成功", "data": {"transaction_id": "pt_001", "amount": 100, "balance_after": 180}},
        "error_example": {"success": False, "detail": {"code": "KAMI_INVALID", "message": "卡密不可用"}},
        "remark": "与自定义面额积分卡配合使用。",
        "doc_markdown": "卡密只能兑换一次，兑换成功后会绑定到当前用户账户。",
        "sort_order": 50,
    },
    {
        "name": "扣除积分",
        "interface_key": "points.consume",
        "method": "POST",
        "path": "/api/v1/user/points/consume",
        "category": "points",
        "description": "业务系统每次消费服务时扣减用户积分，并生成消费流水。",
        "auth_mode": "bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "amount", "type": "integer", "required": True, "description": "扣减积分，必须大于 0"},
            {"name": "biz_id", "type": "string", "required": False, "description": "业务幂等号"},
            {"name": "remark", "type": "string", "required": False, "description": "消费说明"},
            {"name": "metadata", "type": "object", "required": False, "description": "业务扩展数据"},
        ],
        "response_params": [
            {"name": "transaction_id", "type": "string", "required": True, "description": "消费流水号"},
            {"name": "amount", "type": "integer", "required": True, "description": "扣减积分"},
            {"name": "balance_after", "type": "integer", "required": True, "description": "扣减后余额"},
        ],
        "success_example": {"success": True, "message": "积分扣减成功", "data": {"transaction_id": "pt_002", "amount": 10, "balance_after": 170}},
        "error_example": {"success": False, "detail": {"code": "INSUFFICIENT_POINTS", "message": "积分余额不足"}},
        "remark": "积分消费闭环的核心扣减接口。",
        "doc_markdown": "建议业务系统传入 biz_id 做幂等控制，避免重复扣费。",
        "sort_order": 60,
    },
    {
        "name": "积分流水",
        "interface_key": "points.transactions",
        "method": "GET",
        "path": "/api/v1/user/points/transactions",
        "category": "points",
        "description": "查询当前用户充值、消费、退款、调整流水。",
        "auth_mode": "bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "page", "type": "integer", "required": False, "description": "页码"},
            {"name": "page_size", "type": "integer", "required": False, "description": "每页数量"},
        ],
        "response_params": [
            {"name": "items", "type": "array", "required": True, "description": "流水列表"},
            {"name": "total", "type": "integer", "required": True, "description": "总数"},
        ],
        "success_example": {"success": True, "message": "积分流水查询成功", "data": {"total": 1, "items": [{"transaction_type": "consume", "amount": 10}]}},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "用于业务侧展示充值消费明细。",
        "doc_markdown": "流水包含 recharge、consume、refund、adjust 四类。",
        "sort_order": 70,
    },
    {
        "name": "获取 RSA 公钥",
        "interface_key": "sdk.public_key",
        "method": "GET",
        "path": "/api/v1/sdk/public-key",
        "category": "sdk",
        "description": "SDK 调用前获取应用 RSA 公钥，用于加密卡密验证请求。",
        "auth_mode": "app_id",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": [
            {"name": "app_id", "type": "string", "required": True, "description": "应用 App ID"},
        ],
        "response_params": [
            {"name": "public_key", "type": "string", "required": True, "description": "RSA 公钥"},
        ],
        "success_example": {"success": True, "message": "RSA 公钥获取成功", "data": {"public_key": "-----BEGIN PUBLIC KEY-----..."}},
        "error_example": {"success": False, "detail": "应用不存在"},
        "remark": "测试场景 RSA 公钥未初始化时应先确认应用密钥已生成。",
        "doc_markdown": "客户端可缓存公钥，但应用密钥轮换后需要重新获取。",
        "sort_order": 80,
    },
    {
        "name": "卡密验证",
        "interface_key": "sdk.verify",
        "method": "POST",
        "path": "/api/v1/sdk/verify",
        "category": "sdk",
        "description": "SDK 核心验证接口，支持时间卡、次数卡、积分卡等卡密验证和机器码绑定。",
        "auth_mode": "sdk-signature",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": SDK_SECURITY_PARAMS + [
            {"name": "payload.kami", "type": "string", "required": True, "description": "卡密"},
            {"name": "payload.uuid", "type": "string", "required": False, "description": "稳定设备 UUID，建议每台设备固定不变"},
            {"name": "payload.fingerprint", "type": "string", "required": True, "description": "设备指纹"},
            {"name": "payload.user_id", "type": "integer|string", "required": False, "description": "用户授权场景推荐传入；作为稳定绑定标识，用户名变更不影响授权归属"},
            {"name": "payload.username", "type": "string", "required": False, "description": "用户授权场景推荐与 user_id 同时传入；用于后台展示注册用户名并同步改名"},
        ],
        "response_params": [
            {"name": "valid", "type": "boolean", "required": True, "description": "验证是否通过"},
            {"name": "kami_type", "type": "string", "required": True, "description": "卡密类型"},
            {"name": "expires_at", "type": "string", "required": False, "description": "到期时间"},
            {"name": "times_remaining", "type": "integer", "required": False, "description": "剩余次数"},
            {"name": "points_amount", "type": "integer", "required": False, "description": "积分面额"},
        ],
        "success_example": {"success": True, "message": "卡密验证成功", "data": {"valid": True, "kami_type": "day", "expires_at": "2026-08-12T12:00:00"}},
        "error_example": {"success": False, "detail": "卡密无效或设备不匹配"},
        "remark": "用户授权建议同时传 user_id 和 username：绑定识别看 user_id，后台展示看 username；设备授权不需要传用户字段。",
        "doc_markdown": "验证接口继续沿用现有 SDK 加密请求格式，业务字段在 payload 中传输。无注册账号的软件使用默认设备授权，只传 kami、uuid、fingerprint；有账号体系的软件开启用户授权后，推荐同时传 user_id 和 username，user_id 用于稳定绑定，username 用于后台展示和改名同步。",
        "sort_order": 90,
    },
    {
        "name": "次数卡核销",
        "interface_key": "sdk.consume",
        "method": "POST",
        "path": "/api/v1/sdk/consume",
        "category": "sdk",
        "description": "业务系统核销次数卡权益。验证接口只校验授权有效性，只有本接口会扣减次数。",
        "auth_mode": "sdk-signature",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": SDK_SECURITY_PARAMS + [
            {"name": "payload.kami", "type": "string", "required": True, "description": "卡密"},
            {"name": "payload.uuid", "type": "string", "required": False, "description": "稳定设备 UUID，建议与 verify 保持一致"},
            {"name": "payload.fingerprint", "type": "string", "required": True, "description": "设备指纹"},
            {"name": "payload.user_id", "type": "integer|string", "required": False, "description": "用户授权场景推荐传入；必须与验证绑定的同一用户保持一致"},
            {"name": "payload.username", "type": "string", "required": False, "description": "用户授权场景推荐与 user_id 同时传入；用于后台展示注册用户名并同步改名"},
            {"name": "payload.amount", "type": "integer", "required": False, "description": "本次核销次数，默认 1"},
            {"name": "payload.biz_id", "type": "string", "required": False, "description": "业务幂等 ID，重复提交不会重复扣减"},
        ],
        "response_params": [
            {"name": "success", "type": "boolean", "required": True, "description": "是否核销成功"},
            {"name": "consume_id", "type": "string", "required": False, "description": "核销流水 ID"},
            {"name": "times_total", "type": "integer", "required": False, "description": "总次数"},
            {"name": "times_remaining", "type": "integer", "required": False, "description": "剩余次数"},
            {"name": "idempotent", "type": "boolean", "required": False, "description": "是否命中幂等重试"},
        ],
        "success_example": {
            "success": True,
            "message": "核销成功",
            "data": {"consume_id": "tc_xxx", "times_total": 10, "times_remaining": 9},
        },
        "error_example": {"success": False, "detail": "次数卡剩余次数不足"},
        "remark": "推荐业务方每次核销传入稳定 biz_id；用户授权场景继续同时传 user_id 和 username。",
        "doc_markdown": "次数卡应先调用 verify 判断授权有效，再在实际使用权益时调用 consume 扣减次数。用户授权卡密核销时，推荐继续同时传 user_id 和 username，确保扣减记录、授权明细和后台展示归属一致。",
        "sort_order": 95,
    },
    {
        "name": "卡密解绑",
        "interface_key": "sdk.unbind",
        "method": "POST",
        "path": "/api/v1/sdk/unbind",
        "category": "sdk",
        "description": "按应用配置对已绑定机器码的卡密执行解绑。",
        "auth_mode": "sdk-signature",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": SDK_SECURITY_PARAMS + [
            {"name": "kami_code", "type": "string", "required": True, "description": "卡密"},
            {"name": "fingerprint", "type": "string", "required": True, "description": "设备指纹"},
        ],
        "response_params": [
            {"name": "success", "type": "boolean", "required": True, "description": "是否解绑成功"},
            {"name": "unbind_count", "type": "integer", "required": False, "description": "已解绑次数"},
        ],
        "success_example": {"success": True, "message": "卡密解绑成功"},
        "error_example": {"success": False, "detail": "应用未允许解绑"},
        "remark": "仅在应用核心配置允许解绑时生效。",
        "doc_markdown": "解绑可按配置扣减时长或次数。",
        "sort_order": 100,
    },
    {
        "name": "设备限制",
        "interface_key": "sdk.device_limit",
        "method": "POST",
        "path": "/api/v1/sdk/release-device",
        "category": "sdk",
        "description": "SDK 释放当前设备的在线占用名额，用于软件关闭或退出登录后自动释放设备数。",
        "auth_mode": "sdk-signature",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": SDK_SECURITY_PARAMS + [
            {"name": "kami_code", "type": "string", "required": True, "description": "卡密"},
            {"name": "device_uuid", "type": "string", "required": False, "description": "设备 UUID"},
            {"name": "fingerprint", "type": "string", "required": True, "description": "设备指纹"},
        ],
        "response_params": [
            {"name": "success", "type": "boolean", "required": True, "description": "请求是否处理成功"},
            {"name": "released", "type": "boolean", "required": True, "description": "是否释放了当前设备名额"},
            {"name": "current_device_count", "type": "integer", "required": True, "description": "释放后的当前占用设备数"},
            {"name": "max_bind_devices", "type": "integer", "required": True, "description": "当前卡密允许绑定设备数"},
        ],
        "success_example": {
            "success": True,
            "message": "设备名额已释放",
            "released": True,
            "current_device_count": 1,
            "max_bind_devices": 2,
        },
        "error_example": {"success": False, "message": "卡密不存在"},
        "remark": "默认开通。关闭后批次不显示设备绑定限制，SDK 验证也不会占用设备名额。",
        "doc_markdown": "客户端应在用户退出登录、软件正常关闭时调用；异常断开场景后续可通过心跳超时进一步自动释放。",
        "sort_order": 105,
    },
    {
        "name": "应用配置",
        "interface_key": "sdk.app_config",
        "method": "GET",
        "path": "/api/v1/sdk/apps/{app_id}/config",
        "category": "sdk",
        "description": "SDK 获取应用公告、版本、更新地址、安全校验等配置。",
        "auth_mode": "app_id",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": [
            {"name": "app_id", "type": "string", "required": True, "description": "应用 App ID，放在路径中"},
        ],
        "response_params": [
            {"name": "notice_enabled", "type": "boolean", "required": True, "description": "是否启用公告展示"},
            {"name": "notice_title", "type": "string", "required": False, "description": "公告标题"},
            {"name": "notice", "type": "string", "required": False, "description": "应用公告"},
            {"name": "notice_level", "type": "string", "required": True, "description": "公告级别：normal/important/urgent"},
            {"name": "notice_popup", "type": "boolean", "required": True, "description": "是否建议客户端启动时弹窗展示"},
            {"name": "version", "type": "string", "required": False, "description": "最新版本"},
            {"name": "version_info", "type": "string", "required": False, "description": "版本说明或更新内容"},
            {"name": "force_update", "type": "boolean", "required": True, "description": "是否强制更新"},
            {"name": "update_url", "type": "string", "required": False, "description": "应用更新地址，可配置为外链下载地址"},
            {"name": "update_url_type", "type": "string", "required": False, "description": "更新地址类型，如 direct"},
            {"name": "download_button_text", "type": "string", "required": False, "description": "客户端下载按钮文案，默认立即下载"},
            {"name": "files", "type": "array", "required": True, "description": "外链下载文件列表，包含 name、url、type、note"},
            {"name": "security", "type": "object", "required": True, "description": "签名、nonce、时间戳、IP 绑定和解绑策略"},
        ],
        "success_example": {
            "success": True,
            "data": {
                "app_id": "app_xxx",
                "name": "示例应用",
                "notice_enabled": True,
                "notice_title": "公告标题",
                "notice": "公告内容...",
                "notice_level": "important",
                "notice_popup": True,
                "version": "1.0.0",
                "version_info": "修复已知问题",
                "force_update": False,
                "update_url": "https://example.com/download",
                "update_url_type": "external",
                "download_button_text": "立即下载",
                "files": [
                    {
                        "name": "Windows 客户端",
                        "url": "https://example.com/client.zip",
                        "type": "direct",
                        "note": "外链下载",
                    }
                ],
                "security": {
                    "signature_required": True,
                    "nonce_required": True,
                    "timestamp_tolerance_seconds": 300,
                    "ip_lock_enabled": False,
                    "allow_unbind": False,
                    "max_unbind_count": 0,
                },
            },
        },
        "error_example": {"success": False, "detail": "应用不存在"},
        "remark": "业务端可用此接口拉取公告、版本更新策略和外链下载文件。",
        "doc_markdown": "该接口不消费卡密，不改变设备绑定；客户端启动时可按 notice_enabled、notice_title、notice、notice_level、notice_popup 生成公告弹窗，再按 update_url 和 download_button_text 展示立即下载按钮。files 保留给多文件下载列表或旧下载地址兼容。",
        "sort_order": 110,
    },
    {
        "name": "SDK 文件下载",
        "interface_key": "sdk.download",
        "method": "GET",
        "path": "/api/sdk/download",
        "category": "sdk",
        "description": "下载系统内置 SDK 压缩包，支持 Python、JavaScript 和 Java SDK。",
        "auth_mode": "none",
        "content_type": "application/zip",
        "request_headers": [],
        "request_params": [
            {"name": "type", "type": "string", "required": True, "description": "SDK 类型：python、javascript、java"},
        ],
        "response_params": [
            {"name": "file", "type": "binary", "required": True, "description": "SDK zip 压缩包"},
        ],
        "success_example": "返回 application/zip 文件流",
        "error_example": {"success": False, "detail": "SDK 文件不存在"},
        "remark": "用于下载本系统附带的 SDK 包；业务软件自己的外链下载地址请使用应用配置接口中的 files 或 update_url。",
        "doc_markdown": "该接口返回文件流，不返回 JSON。示例：/api/sdk/download?type=javascript。",
        "sort_order": 115,
    },
    {
        "name": "行为上报",
        "interface_key": "sdk.report",
        "method": "POST",
        "path": "/api/v1/sdk/report",
        "category": "sdk",
        "description": "SDK 上报登录、启动、异常等行为日志。",
        "auth_mode": "sdk-signature",
        "content_type": "application/json",
        "request_headers": [],
        "request_params": SDK_SECURITY_PARAMS + [
            {"name": "event_type", "type": "string", "required": True, "description": "事件类型"},
            {"name": "event_data", "type": "object", "required": False, "description": "事件数据"},
        ],
        "response_params": [
            {"name": "success", "type": "boolean", "required": True, "description": "是否接收成功"},
        ],
        "success_example": {"success": True, "message": "行为上报成功"},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "用于风险分析和行为审计。",
        "doc_markdown": "高频上报由后端异步落日志，避免影响验证接口。",
        "sort_order": 120,
    },
    {
        "name": "生成卡密",
        "interface_key": "admin.kamis.batch",
        "method": "POST",
        "path": "/api/v1/admin/kamis/batch",
        "category": "admin",
        "description": "管理端批量生成卡密，支持自定义面额、批次号、机器码绑定模式和批次授权策略。",
        "auth_mode": "admin-bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "app_id", "type": "string", "required": True, "description": "应用 App ID"},
            {"name": "count", "type": "integer", "required": True, "description": "生成数量"},
            {"name": "kami_type", "type": "string", "required": True, "description": "卡密类型"},
            {"name": "points_amount", "type": "integer", "required": False, "description": "积分卡面额"},
            {"name": "machine_bind_mode", "type": "string", "required": False, "description": "机器码绑定模式"},
            {"name": "authorization_owner", "type": "string", "required": False, "description": "授权归属策略：device/user/auto"},
            {"name": "user_bind_mode", "type": "string", "required": False, "description": "用户绑定策略：none/auto/required"},
        ],
        "response_params": [
            {"name": "batch_no", "type": "string", "required": True, "description": "批次号"},
            {"name": "kamis", "type": "array", "required": True, "description": "生成的卡密列表"},
        ],
        "success_example": {"success": True, "message": "卡密生成成功", "data": {"batch_no": "B20260712001", "kamis": ["YKABC123"]}},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "前端按钮命名为新建卡密，本质仍按批次生成。",
        "doc_markdown": "积分卡创建时必须传 points_amount，面额可由管理员自定义。",
        "sort_order": 130,
    },
    {
        "name": "卡密列表",
        "interface_key": "admin.kamis.list",
        "method": "GET",
        "path": "/api/v1/admin/kamis",
        "category": "admin",
        "description": "管理端按应用、批次、状态、类型、关键字查询卡密。",
        "auth_mode": "admin-bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "app_id", "type": "string", "required": False, "description": "应用 App ID"},
            {"name": "batch_no", "type": "string", "required": False, "description": "批次号"},
            {"name": "status", "type": "integer", "required": False, "description": "卡密状态"},
            {"name": "keyword", "type": "string", "required": False, "description": "卡密、用户、备注关键字"},
        ],
        "response_params": [
            {"name": "items", "type": "array", "required": True, "description": "卡密列表"},
            {"name": "total", "type": "integer", "required": True, "description": "总数"},
        ],
        "success_example": {"success": True, "message": "卡密列表获取成功", "data": {"total": 1, "items": [{"kami_code": "YKABC123"}]}},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "卡密管理页使用该接口展示不同批次的使用用户、权益余量、到期时间等字段。",
        "doc_markdown": "列表字段会随卡密类型返回时间、次数或积分相关信息。",
        "sort_order": 140,
    },
    {
        "name": "批次列表",
        "interface_key": "admin.kamis.batches",
        "method": "GET",
        "path": "/api/v1/admin/kamis/batches",
        "category": "admin",
        "description": "管理端查看卡密批次汇总。",
        "auth_mode": "admin-bearer",
        "content_type": "application/json",
        "request_headers": AUTH_HEADER,
        "request_params": [
            {"name": "app_id", "type": "string", "required": False, "description": "应用 App ID"},
        ],
        "response_params": [
            {"name": "items", "type": "array", "required": True, "description": "批次列表"},
            {"name": "total", "type": "integer", "required": True, "description": "批次数量"},
        ],
        "success_example": {"success": True, "message": "批次列表获取成功", "data": {"total": 1, "items": [{"batch_no": "B20260712001"}]}},
        "error_example": COMMON_ERROR_EXAMPLE,
        "remark": "批次管理页使用该接口进入对应批次卡密统一管理。",
        "doc_markdown": "批次汇总包含总数、已用、剩余、机器码限制等信息。",
        "sort_order": 150,
    },
]
